services:
  big-ear:
    env_file:
      - .env
    environment:
        - NATS_URL=nats://nats:4222
        - LAST_DATA_DIR=/home/appuser/lastdata
    build:
      context: .
      target: final
    depends_on:
      - nats
    volumes:
      - last_data:/home/appuser/last_data

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats:/data
    command:
      - "--name=nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
volumes:
  nats:
  last_data:
